// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"fmt"
)

type Status string

const (
	StatusDraft     Status = "draft"
	StatusDeleted   Status = "deleted"
	StatusPublished Status = "published"
)

func (e *Status) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Status(s)
	case string:
		*e = Status(s)
	default:
		return fmt.Errorf("unsupported scan type for Status: %T", src)
	}
	return nil
}

type News struct {
	ID            int32        `json:"id"`
	Title         string       `json:"title"`
	Author        string       `json:"author"`
	Status        Status       `json:"status"`
	PublishedDate sql.NullTime `json:"published_date"`
	Article       string       `json:"article"`
}

type NewsTag struct {
	TagID  sql.NullInt32 `json:"tag_id"`
	NewsID sql.NullInt32 `json:"news_id"`
}

type Tag struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Topic struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}
