// Code generated by sqlc. DO NOT EDIT.
// source: topic.sql

package db

import (
	"context"
)

const createTopic = `-- name: CreateTopic :one
INSERT INTO topic (
    id,
    name
) VALUES (
    $1, $2
) RETURNING id, name
`

type CreateTopicParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRowContext(ctx, createTopic, arg.ID, arg.Name)
	var i Topic
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
